[tool.poetry]
name = "dorado-scheduling"
version = "0.1.0"
description = "Dorado observation planning and scheduling simulations"
authors = ["Leo Singer <leo.singer@ligo.org>"]
license = "NOSA"
packages = [
    {include = "dorado"}]
include = [
    "dorado/scheduling/data/*.txt",
    "dorado/scheduling/data/*.md"]

[tool.poetry.dependencies]
python = "^3.7"
skyfield = "*"
astropy = "<4.0.2"  # https://github.com/astropy/astroplan/issues/479
astroplan = {version = "*", allow-prereleases = true}
mip = {git = "https://github.com/lpsinger/python-mip", branch = "local"}  # https://github.com/coin-or/python-mip/pull/149, https://github.com/coin-or/python-mip/pull/151
"ligo.skymap" = "^0.5.0"
healpy = "*"
zstandard = "*"

[tool.poetry.dev-dependencies]
flake8 = "*"

[tool.poetry.scripts]
dorado-scheduling = "dorado.scheduling.scripts.main:main"
dorado-scheduling-prepare = "dorado.scheduling.scripts.prepare:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
