[tool.poetry]
name = "dorado-scheduling"
version = "0.1.0"
description = "Dorado observation planning and scheduling simulations"
authors = ["Leo Singer <leo.singer@ligo.org>"]
license = "NOSA"
packages = [
    {include = "dorado"}]
include = [
    "dorado/scheduling/data/*.txt",
    "dorado/scheduling/data/*.md"]

[tool.poetry.dependencies]
python = "^3.7"
skyfield = "*"
astropy = "^4.1"
astroplan = "^0.7"
mip = {git = "https://github.com/lpsinger/python-mip", branch = "setuptools-scm"}  # https://github.com/coin-or/python-mip/pull/151
"ligo.skymap" = "^0.5.0"
healpy = "*"
seaborn = "*"
shapely = "*"  # for ligo.skymap.plot.poly.cut_prime_meridian
zstandard = "*"

[tool.poetry.dev-dependencies]
flake8 = "*"
ipykernel = "*"

[tool.poetry.scripts]
dorado-scheduling = "dorado.scheduling.scripts.main:main"
dorado-scheduling-animate = "dorado.scheduling.scripts.animate:main"
dorado-scheduling-prepare = "dorado.scheduling.scripts.prepare:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
